name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Check Format
        run: crystal tool format --check

      - name: Run Specs
        run: crystal spec

      - name: Install Ameba
        run: shards install

      - name: Run Lints
        run: bin/ameba --except Layout/TrailingWhitespace
